name: p2p_task
description: A privacy-aware P2P task manager.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0 # Copyright; Redistribute with notice
  device_info_plus: ^1.0.1 # Copyright; Redistribute with notice
  flutter_simple_dependency_injection: ^2.0.0 # MIT License
  flutter_slidable: ^0.6.0 # MIT License
  json_annotation: ^4.0.1 # Copyright; Redistribute with notice
  network_info_plus: ^1.0.1 # Copyright; Redistribute with notice
  package_info_plus: ^1.0.3 # Copyright; Redistribute with notice
  path_provider: ^2.0.2 # Copyright; Redistribute with notice
  permission_handler: ^8.0.0+2 # MIT License
  provider: ^5.0.0 # MIT License
  pull_to_refresh: ^2.0.0 # MIT License
  qr_code_scanner: ^0.5.1 # Copyright; Redistribute with notice
  qr_flutter: ^4.0.0 # BSD 3
  shared_preferences: ^2.0.6 # Copyright; Redistribute with notice
  sembast: ^3.1.0+2 # Copyright; Redistribute with notice
  sembast_web: ^2.0.0+2 # Copyright; Redistribute with notice
  shelf: ^1.1.4 # Copyright; Redistribute with notice
  shelf_web_socket: ^1.0.1 # Copyright; Redistribute with notice
  uuid: ^3.0.4 # MIT-ish License
  web_socket_channel: ^2.1.0 # Copyright; Redistribute with notice

  lww_crdt:
    path: lww_crdt
    version: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3 # MIT License
  intl: ^0.17.0 # Copyright; Redistribute with notice
  pedantic: ^1.11.0 # Copyright; Redistribute with notice

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.10
  fake_async: ^1.2.0

  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_lints: ^1.0.3

  dart_code_metrics: ^4.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
