name: p2p_task
description: A privacy-aware P2P task manager.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0 # BSD License
  device_info_plus: ^1.0.1 # BSD License
  flutter_simple_dependency_injection: ^2.0.0 # MIT License
  flutter_slidable: ^0.6.0 # MIT License
  json_annotation: ^4.0.1 # BSD License
  network_info_plus: ^1.0.1 # BSD License
  package_info_plus: ^1.0.3 # BSD License
  path_provider: ^2.0.2 # BSD License
  permission_handler: ^8.0.0+2 # MIT License
  provider: ^5.0.0 # MIT License
  pull_to_refresh: ^2.0.0 # MIT License
  qr_code_scanner: ^0.5.1 # BSD License
  qr_flutter: ^4.0.0 # BSD License
  shared_preferences: ^2.0.6 # BSD License
  sembast: ^3.1.0+2 # BSD License
  sembast_web: ^2.0.0+2 # BSD License
  shelf: ^1.1.4 # BSD License
  shelf_web_socket: ^1.0.1 # BSD License
  uuid: ^3.0.4 # MIT License
  web_socket_channel: ^2.1.0 # BSD License
  pointycastle: ^3.1.2 # MIT License
  asn1lib: ^1.0.2 # BSD License
  encrypt: ^5.0.0 # BSD License

  lww_crdt:
    path: lww_crdt
    version: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3 # MIT License
  intl: ^0.17.0 # BSD License
  pedantic: ^1.11.0 # BSD License

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.10 # Apache 2.0 License
  fake_async: ^1.2.0 # Apache 2.0 License

  build_runner: ^2.0.4 # BSD License
  json_serializable: ^4.1.3 # BSD License
  flutter_lints: ^1.0.3 # BSD License

  dart_code_metrics: ^4.0.0 # MIT License

flutter:
  assets:
    - assets/

  uses-material-design: true
