name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter pub run build_runner build
      - run: flutter analyze
      - run: flutter test

  build-android:
    runs-on: ubuntu-latest
    needs: test
    if:
      github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && needs.test.result == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build apk
      - uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: build/app/outputs/apk/release

  build-ios:
    runs-on: macos-latest
    needs: test
    if:
      github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && needs.test.result == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: build/ios/iphoneos

  deploy-web:
    runs-on: ubuntu-latest
    needs: test
    if:
      github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && needs.test.result == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build web
      - run: sed -i 's#<base href="/">#<base href="/P2P-Task/">#g' build/web/index.html
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: build/web
